export function build(...args: unknown[]): unknown;
export function get(...args: unknown[]): unknown;
export function list(...args: unknown[]): unknown;
export function deleteGraph(...args: unknown[]): unknown;
export function analyze(...args: unknown[]): unknown;
export function recommend(...args: unknown[]): unknown;
export function visualize(...args: unknown[]): unknown;
export function saveGraph(...args: unknown[]): unknown;
export const buildGraph: unknown;
export const serializeGraph: unknown;
export const deserializeGraph: unknown;
export const analyzeGraph: unknown;
export const findMutualConnections: unknown;
export const getMutualConnectionsFor: unknown;
export const findBridgeAccounts: unknown;
export const detectClusters: unknown;
export const computeInfluenceScores: unknown;
export const getInfluenceRanking: unknown;
export const findGhostFollowers: unknown;
export const analyzeOrbits: unknown;
export const getRecommendations: unknown;
export const toD3: unknown;
export const toGEXF: unknown;
export const toHTML: unknown;
declare const _default: Record<string, unknown>;
export default _default;
