export { analyzeSentiment, analyzeBatch, aggregateResults } from './sentiment.js';
export { createMonitor, stopMonitor, getMonitor, getMonitorHistory, listMonitors, removeMonitor, stopAll } from './reputation.js';
export { checkAlerts, getAlerts, clearAlerts, emitHypeAnomalyAlert } from './alerts.js';
export { generateReport } from './reports.js';
export { analyzeTweetPriceCorrelation, alignTweetsWithPrices, computeCorrelationStats, fetchCoinGeckoPrices, fetchGeckoTerminalPrices } from './priceCorrelation.js';
export { saveAccountSnapshot, saveTweetSnapshot, saveDailyEngagement, getAccountHistory, getTweetHistory, getGrowthRate, compareAccounts, exportHistory } from './historyStore.js';
export { startAutoSnapshot, stopAutoSnapshot, listActiveSnapshots, stopAllSnapshots } from './autoSnapshot.js';
export { analyzeOverlap, multiOverlap, findSimilarAudience, getAudienceInsights } from './audienceOverlap.js';
export { createTokenMentionPipeline } from './tokenMentionPipeline.js';
export { createHypeAuthenticity, getDefaultHypeAuthenticity, HYPE_ALERT_MONITOR_ID } from './hypeAuthenticity.js';
export { createMindshareEngine, getDefaultMindshare } from './mindshare.js';
export { syncFollowers, tagContact, untagContact, addNote, scoreContact, autoScore, searchContacts, filterContacts, createSegment, getSegment, listSegments, bulkTag, getContactTimeline, exportSegment } from './followerCRM.js';
declare const _default: unknown;
export default _default;
