// Copyright (c) 2024-2026 nich (@nichxbt). Licensed under the Apache License, Version 2.0.
/**
 * `medirus completion <shell>` — print a shell completion script.
 *
 * With fifty-plus commands and several hundred flags, typing the CLI from
 * memory is the slowest way to use it. The scripts below are generated from
 * the live Commander tree rather than hand-maintained, so a command added
 * tomorrow completes tomorrow with no extra step and no list to forget.
 *
 * Completion covers three levels: top-level command names, sub-command names
 * (`medirus plugin <tab>`), and the flags of whichever command is being typed.
 *
 * @author nich (@nichxbt) - https://github.com/nirholas
 */

import chalk from 'chalk';

/** Shells with a generator here. */
export const SUPPORTED_SHELLS = ['bash', 'zsh', 'fish'];

/**
 * Flatten the Commander tree into completion data.
 *
 * @param {import('commander').Command} program
 * @returns {{name: string, description: string, options: string[], subcommands: {name: string, description: string, options: string[]}[]}[]}
 */
export function collectCommands(program) {
  const optionFlags = (command) =>
    command.options.flatMap((option) =>
      // `-l, --limit <n>` yields both `-l` and `--limit`.
      option.flags
        .split(/[\s,]+/)
        .filter((token) => token.startsWith('-'))
        .map((token) => token.replace(/[[<].*$/, ''))
    );

  return program.commands
    .filter((command) => command.name() !== 'help')
    .map((command) => ({
      name: command.name(),
      description: (command.description() ?? '').split('\n')[0],
      options: [...new Set(optionFlags(command))],
      subcommands: command.commands.map((sub) => ({
        name: sub.name(),
        description: (sub.description() ?? '').split('\n')[0],
        options: [...new Set(optionFlags(sub))],
      })),
    }));
}

/** Quote a description for safe embedding in a shell string literal. */
function escapeDescription(text) {
  return String(text).replace(/'/g, "'\\''").replace(/[\r\n]+/g, ' ');
}

/**
 * Escape a description for zsh's `name:description` pair format.
 *
 * An unescaped colon splits the pair in the wrong place, so a description like
 * "Account report: engagement rate..." silently truncates the completion to
 * "Account report" and leaves the rest as garbage. `_describe` wants the colon
 * backslash-escaped.
 */
function escapeZshDescription(text) {
  return escapeDescription(text).replace(/:/g, '\\:');
}

function generateBash(commands, globalOptions) {
  const names = commands.map((command) => command.name).join(' ');

  const subcommandCases = commands
    .filter((command) => command.subcommands.length > 0)
    .map(
      (command) =>
        `      ${command.name}) __medirus_reply "${command.subcommands.map((sub) => sub.name).join(' ')} ${command.options.join(' ')}" ;;`
    )
    .join('\n');

  const optionCases = commands
    .filter((command) => command.subcommands.length === 0 && command.options.length > 0)
    .map((command) => `      ${command.name}) __medirus_reply "${command.options.join(' ')}" ;;`)
    .join('\n');

  return `# medirus bash completion. Generated by \`medirus completion bash\`.
# Install:  medirus completion bash > /etc/bash_completion.d/medirus
# Or:       echo 'source <(medirus completion bash)' >> ~/.bashrc

__medirus_reply() {
  COMPREPLY=( $(compgen -W "$1" -- "\${COMP_WORDS[COMP_CWORD]}") )
}

_medirus() {
  local cur prev
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  # First word after the binary: a command name or a global flag.
  if [ "$COMP_CWORD" -eq 1 ]; then
    __medirus_reply "${names} ${globalOptions.join(' ')}"
    return
  fi

  # A flag is being typed: offer this command's flags.
  if [[ "$cur" == -* ]]; then
    local cmd="\${COMP_WORDS[1]}"
    case "$cmd" in
${optionCases}
${subcommandCases}
      *) __medirus_reply "${globalOptions.join(' ')}" ;;
    esac
    return
  fi

  # Second word: sub-commands of the command already typed.
  if [ "$COMP_CWORD" -eq 2 ]; then
    case "$prev" in
${subcommandCases}
    esac
  fi
}

complete -F _medirus medirus
`;
}

function generateZsh(commands, globalOptions) {
  const commandLines = commands
    .map(
      (command) => `    '${command.name}:${escapeZshDescription(command.description)}'`
    )
    .join('\n');

  const subcommandBlocks = commands
    .filter((command) => command.subcommands.length > 0)
    .map((command) => {
      const subs = command.subcommands
        .map((sub) => `        '${sub.name}:${escapeZshDescription(sub.description)}'`)
        .join('\n');
      return `      ${command.name})
        local -a subs
        subs=(
${subs}
        )
        _describe 'subcommand' subs
        ;;`;
    })
    .join('\n');

  return `#compdef medirus
# medirus zsh completion. Generated by \`medirus completion zsh\`.
# Install:  medirus completion zsh > "\${fpath[1]}/_medirus"
# Or:       echo 'source <(medirus completion zsh)' >> ~/.zshrc

_medirus() {
  local -a commands
  commands=(
${commandLines}
  )

  _arguments -C \\
    '1: :->command' \\
    '*:: :->args'

  case $state in
    command)
      _describe 'command' commands
      ;;
    args)
      case $words[1] in
${subcommandBlocks}
        *)
          _values 'option' ${globalOptions.map((flag) => `'${flag}'`).join(' ')}
          ;;
      esac
      ;;
  esac
}

compdef _medirus medirus
`;
}

function generateFish(commands) {
  const lines = commands.map(
    (command) =>
      `complete -c medirus -n __fish_use_subcommand -a ${command.name} -d '${escapeDescription(command.description)}'`
  );

  for (const command of commands) {
    for (const sub of command.subcommands) {
      lines.push(
        `complete -c medirus -n '__fish_seen_subcommand_from ${command.name}' -a ${sub.name} -d '${escapeDescription(sub.description)}'`
      );
    }
    for (const flag of command.options) {
      const dashless = flag.replace(/^-+/, '');
      const kind = flag.startsWith('--') ? '-l' : '-s';
      lines.push(
        `complete -c medirus -n '__fish_seen_subcommand_from ${command.name}' ${kind} ${dashless}`
      );
    }
  }

  return `# medirus fish completion. Generated by \`medirus completion fish\`.
# Install:  medirus completion fish > ~/.config/fish/completions/medirus.fish

${lines.join('\n')}
`;
}

/**
 * Generate the completion script for a shell.
 *
 * @param {import('commander').Command} program
 * @param {'bash'|'zsh'|'fish'} shell
 * @returns {string}
 */
export function generateCompletion(program, shell) {
  const commands = collectCommands(program);
  const globalOptions = program.options.flatMap((option) =>
    option.flags
      .split(/[\s,]+/)
      .filter((token) => token.startsWith('-'))
      .map((token) => token.replace(/[[<].*$/, ''))
  );

  switch (shell) {
    case 'bash':
      return generateBash(commands, globalOptions);
    case 'zsh':
      return generateZsh(commands, globalOptions);
    case 'fish':
      return generateFish(commands);
    default:
      throw new Error(
        `Unsupported shell "${shell}". Supported: ${SUPPORTED_SHELLS.join(', ')}`
      );
  }
}

/**
 * Register the completion command.
 *
 * @param {import('commander').Command} program
 */
export function registerCompletionCommand(program) {
  program
    .command('completion [shell]')
    .description('Print a tab-completion script for bash, zsh, or fish')
    .addHelpText(
      'after',
      `
Install:
  bash   medirus completion bash > /etc/bash_completion.d/medirus
         # or, without root:
         echo 'source <(medirus completion bash)' >> ~/.bashrc

  zsh    medirus completion zsh > "\${fpath[1]}/_medirus" && compinit
         # or:
         echo 'source <(medirus completion zsh)' >> ~/.zshrc

  fish   medirus completion fish > ~/.config/fish/completions/medirus.fish

The script is generated from the live command tree, so it stays correct as
commands are added. Regenerate it after upgrading Medirus.
`
    )
    .action((shell) => {
      if (!shell) {
        const detected = detectShell();
        console.error(
          chalk.yellow('Tell me which shell:'),
          chalk.cyan(`medirus completion ${detected ?? '<bash|zsh|fish>'}`)
        );
        console.error(chalk.gray(`Supported: ${SUPPORTED_SHELLS.join(', ')}`));
        console.error(chalk.gray('Run `medirus completion --help` for install instructions.'));
        process.exitCode = 1;
        return;
      }

      const normalized = String(shell).toLowerCase();
      if (!SUPPORTED_SHELLS.includes(normalized)) {
        console.error(chalk.red(`Unsupported shell "${shell}".`));
        console.error(chalk.gray(`Supported: ${SUPPORTED_SHELLS.join(', ')}`));
        process.exitCode = 1;
        return;
      }

      // Only the script goes to stdout, so `> file` and `source <(...)` both work.
      process.stdout.write(generateCompletion(program, normalized));
    });
}

/** Best guess at the user's shell, used only to make the error message concrete. */
function detectShell() {
  const shellPath = process.env.SHELL ?? '';
  return SUPPORTED_SHELLS.find((shell) => shellPath.endsWith(shell)) ?? null;
}
